services:
  web:
    image: python:3.12-slim
    container_name: panelweb-web
    working_dir: /app
    command: >
      bash -lc "
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn adminhub.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: panelweb-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

